### PR TITLE
feat: add yaml mime type

### PR DESCRIPTION
**Pull request by NiveditaBhat**
**What kind of change does this PR introduce?**
- [ ] Bug Fix
- [x] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [ ] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**
- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**
Yaml file types are not recognised

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by rolandjitsu** [comment]
Already included.

**Comment by rolandjitsu** [comment]
See https://github.com/react-dropzone/file-selector/commit/24faa1ba5175efb08d6336946c30d03327a45a58 .

**Comment by kibertoad** [comment]
@rolandjitsu yes, but I don't see new release on npm

**Comment by rolandjitsu** [comment]
> @rolandjitsu yes, but I don't see new release on npm

That's because the CI pipeline is failing. I'll have to check why, hopefully tomorrow.

**Comment by kibertoad** [comment]
@rolandjitsu Any update on this?

**Pull request closed without merging**
