### PR TITLE
Add UT to reproduces #106

### PR DESCRIPTION
**Pull request by buenjybar**
**What kind of change does this PR introduce?**

- [x] Bug Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [ ] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**

- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**

- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**
Explain the **motivation** for making this change. What existing problem does the pull request solve?
Try to link to an open issue for more information.

Try to reproduce bug #106 (https://github.com/react-dropzone/file-selector/issues/106)

**Does this PR introduce a breaking change?**
If this PR introduces a breaking change, please describe the impact and a migration path for existing applications.

**Other information**

### CODE REVIEW

**Comment by rolandjitsu** [comment]
Hmm ... I wonder why checks haven't run 😕

**Comment by jonkoops** [comment]
They [need to be approved](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks), which only maintainers can do. This is for security reasons so that people cannot change workflows in a way that would be considered insecure.

**Comment by rolandjitsu** [comment]
> They [need to be approved](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks), which only maintainers can do. This is for security reasons so that people cannot change workflows in a way that would be considered insecure.

I think the new UI doesn't have that.

Screenshot 2024-11-09 at 20 56 23

**Comment by jonkoops** [comment]
Oh interesting, I am still on the old one so I do see it, of course I can't start it as I don't have the permission to do so.

**Comment by rolandjitsu** [comment]
@buenjybar with https://github.com/react-dropzone/file-selector/pull/107, you'll now get a promise rejection with:
```
"[object Object] is not a File"
```

See [diff](https://github.com/react-dropzone/file-selector/pull/107/files#diff-c375cc3212862098a440d985d025a7350a7e2ae65cb9ca95d3f7f9e468906ba5R311).

So you'll need to handle that. But what that test means, essentially, is that the object you get is not actually a file, see [return value](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle#return_value):
> A [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
> 
> If the item's [kind](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/kind) property is "file", and this item is accessed in the [dragstart](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragstart_event) or [drop](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event) event handlers, then the returned promise is fulfilled with a [FileSystemFileHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle) if the dragged item is a file or a [FileSystemDirectoryHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle) if the dragged item is a directory.
> 
> Otherwise, the promise fulfills with null.

And there's no way to reach that point with any other event than a `drop` because there's a guard for that:
```js
        // According to https://html.spec.whatwg.org/multipage/dnd.html#dndevents,
        // only 'dragstart' and 'drop' has access to the data (source node)
        if (type !== 'drop') {
            return items;
        }
        const files = await Promise.all(items.map(toFilePromises));
```

If this happens during cypress tests, it might be worth seeing if there's something about that which may be causing these issues. Are you using something like https://www.cypress.io/blog/uploading-files-with-selectfile?

**Comment by buenjybar** [comment]
It seems that cypress is using the **dispatchEvent** with the following event type: `dragenter`

so it is never catch by this code :
```
        // According to https://html.spec.whatwg.org/multipage/dnd.html#dndevents,
        // only 'dragstart' and 'drop' has access to the data (source node)
        if (type !== 'drop') {
            return items;
        }
        const files = await Promise.all(items.map(toFilePromises));
```

I checked in this [project](https://github.com/buenjybar/react-dropzone-issue106/tree/master/my-app) the items variable just above look like this
image

**Comment by rolandjitsu** [comment]
@buenjybar are you triggering a drop event?

**Comment by rolandjitsu** [comment]
I've also just tried it in [react-dropzone-nextjs](https://github.com/react-dropzone/react-dropzone-nextjs/tree/test/cypress) and I can also see the error. I'll try the patch in https://github.com/react-dropzone/file-selector/pull/107 and see if that works.

**Comment by rolandjitsu** [comment]
@buenjybar I also suggest opening a ticket with cypress and inform them of the current behaviour. We expect that the promise resolves to a file, but it looks like it doesn't.

We could add a check in our code for `window.Cypress` and then handle that case ... but I feel that they should tell us how to deal with that.

It might also be a permission thing or https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts ...

**Comment by rolandjitsu** [comment]
https://github.com/cypress-io/cypress/issues/669 may also be helpful.

**Comment by buenjybar** [comment]
Obsolete, It has been fixed in 2.1.2

**Pull request closed without merging**
