### PR TITLE
chore: replace legacy Yarn with NPM

### PR DESCRIPTION
**Pull request by jonkoops**
**What kind of change does this PR introduce?**
- [ ] Bug Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [x] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**
- [x] Yes, I've updated the documentation
- [ ] Not relevant

**Summary**
Replaces the [legacy version of Yarn](https://yarnpkg.com/getting-started/qa#why-is-the-yarn-package-on-npm-still-on-1x) with regular NPM. This removes a now unsupported version of Yarn and makes it easier for folks looking to make a contribution since NPM will be installed on their system alongside with Node.js.

I considered using the new version of Yarn, but it would require users to enable [Corepack](https://nodejs.org/api/corepack.html), which is slated to be removed from Node.js in the next major. Using NPM simplifies things for users wishing to contribute.

Explain the **motivation** for making this change. What existing problem does the pull request solve?
Try to link to an open issue for more information.

**Does this PR introduce a breaking change?**
No.

**Other information**
None.

### CODE REVIEW

**Comment by jonkoops** [comment]
Looks like some older versions of Node.js don't like the new lockfile format, I will add some conditions there and mark this PR as a draft in the meantime.

**Comment by jonkoops** [comment]
Managed to fix the issue by installing a more recent versions of NPM that is compatible with Node.js 14 conditionally. @rolandjitsu WDYT?

**Comment by rolandjitsu** [comment]
@jonkoops I still use yarn 😄  I don't think it's deprecated, it's a choice users can make via corepack (on latest node, a `corepack enable` will allow users to use yarn - on first use it installs the required version).

And we can also ensure that users use a specific version of yarn by adding a `packageManager` property in `package.json`.

**Comment by jonkoops** [comment]
The only actively maintained version of Yarn is v4, the legacy version used here is v1, which has not been maintained since 2017. If you'd like I can upgrade the project with Yarn v4 instead, but it will come with some caveats:

- Users will have to [enable corepack](https://nodejs.org/api/corepack.html#enabling-the-feature) increasing the barrier to entry over NPM
- Corepack [will be removed](https://socket.dev/blog/node-js-takes-steps-towards-removing-corepack) from Node.js in version 23, requiring an additional installation step.

Let me know what you'd like to do.

**Comment by rolandjitsu** [comment]
@jonkoops I think it makes sense to transition back to npm in that case.

**Comment by jonkoops** [comment]
Can you merge this one in @rolandjitsu, or are there some changes you'd like to add? I have some other work ready to upgrade the GitHub Actions to the latest version that depends on this PR :)

**Review by rolandjitsu — APPROVED** [review]

**Pull request merged**
