### PR TITLE
chore!: drop support for Internet Explorer

### PR DESCRIPTION
**Pull request by jonkoops**
**What kind of change does this PR introduce?**
- [ ] Bug Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [x] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**
- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**
Removes conditional code and tests for Internet Explorer and drops support for it.

**Does this PR introduce a breaking change?**
Yes, it removes support for Internet Explorer entirely.

**Other information**
Not relevant.

### CODE REVIEW

**Comment by jonkoops** [comment]
@rolandjitsu this one is ready to go, can I ask you for a review?

**Comment by rolandjitsu** [comment]
There's apparently an IE mode in Edge that's supported until 2029 (see [internet explorer 11 has retired](https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/))
> And of course, we have committed to supporting IE mode in Microsoft Edge through at least 2029.

Not sure what that translates to. There may also be clients out there that are still using IE 🤔 

I just thought that's worth mentioning it.

**Review by rolandjitsu — APPROVED** [review]
It look ok. I just wonder if we should just drop support for IE11 🤔

**Comment by jonkoops** [comment]
We're already shipping syntax that is no longer supported in Internet Explorer, so this realistically won't be an issue. Also the compatibility mode in Edge is intended to be used only on an allow-list basis for sites that experience compatibility issues, not as a blanket feature to enable on all sites, as that would most certainly cause most sites not to function.

**Comment by jonkoops** [comment]
@rolandjitsu any objection against merging this one? I have a couple of PRs that will build off this to resolve the remaining linting issues.

**Pull request merged**
