### PR TITLE
refactor!: drop UMD distribution from package

### PR DESCRIPTION
**Pull request by jonkoops**
BREAKING CHANGE: removes the UMD distribution from the package

**What kind of change does this PR introduce?**
- [ ] Bug Fix
- [ ] Feature
- [x] Refactoring
- [ ] Style
- [ ] Build
- [ ] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [ ] Yes, my code is well tested
- [x] Not relevant

**If relevant, did you update the documentation?**
- [x] Yes, I've updated the documentation
- [ ] Not relevant

**Summary**
Removes the UMD distribution from the package in favor of using the module variant directly. This also removes the need to carry Rollup as a dependency. Documentation has also been cleaned up to reflect these changes.

**Does this PR introduce a breaking change?**
Yes, the UMD distrubution will no longer work, users should replace it with a direct import instead.

**Other information**
None.

### CODE REVIEW

**Comment by jonkoops** [comment]
@rolandjitsu considering this is another breaking change this will likely trigger the semantic release bot to do a `2.0.0` release. Originally I was planning on doing all the breaking changes in a pre-1.0 version, and then doing a stable release, but now this is no longer possible we should probably disable the release pipeline or make it do 2.0 pre-releases for now.

**Comment by jonkoops** [comment]
See https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/release-workflow/pre-releases.md

**Comment by jonkoops** [comment]
Looks like setting up a `beta` branch would do this for us. @rolandjitsu could you create a `beta` branch? I'll change the PR to target it instead.

**Comment by rolandjitsu** [comment]
> Looks like setting up a `beta` branch would do this for us. @rolandjitsu could you create a `beta` branch? I'll change the PR to target it instead.

I can. We also need the right config in the workflows to allow running from beta and a releases config file.

**Review by rolandjitsu — APPROVED** [review]
LGTM

**Comment by jonkoops** [comment]
Set up a pre-release workflow under #94, once that is merged we can set up the `beta` branch from it.

**Comment by jonkoops** [comment]
This one is ready to be merged, I've rebased it against the `beta` branch and changed the target.

**Comment by rolandjitsu** [comment]
> This one is ready to be merged, I've rebased it against the `beta` branch and changed the target.

Ok. Gonna have a look now.

**Review by rolandjitsu — APPROVED** [review]

**Pull request merged**
